name = "bcc-safety-dashboard2"
main = "src/worker.js"
compatibility_date = "2026-05-15"

[durable_objects]
bindings = [
  { name = "SAFETY_DASHBOARD", class_name = "DashboardDurableObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DashboardDurableObject"]
